global:
  scrape_interval: 30s
scrape_configs:
  - job_name: 'gateway'
    scrape_interval: 30s
    static_configs:
      - targets: ['gateway:8000']

  - job_name: 'docker'
    scrape_interval: 30s
    static_configs:
      - targets: ["host.docker.internal:9323"]
  - job_name: 'tournaments'
    scrape_interval: 30s
    static_configs:
      - targets: ['tournaments:8000']
  - job_name: 'usermanagement'
    scrape_interval: 30s
    static_configs:
      - targets: ['usermanagement:8000']