#!/bin/bash

set -o errexit
set -o nounset

cd /app
#python manage.py makemigrations user
#python manage.py makemigrations tournamentsapp
#python manage.py migrate
celery -A tournaments worker -l INFO
